

insert into `tsys_config` (`type`, `ckey`, `cvalue`, `note`, `updater`, `update_datetime`, `remark`, `company_code`, `system_code`) values('1','HDGMSJF','100','活动报名','admin',now(),'活动报名送积分','CD-ZWZJ000012','CD-ZWZJ000012');
insert into `tsys_config` (`type`, `ckey`, `cvalue`, `note`, `updater`, `update_datetime`, `remark`, `company_code`, `system_code`) values('1','SKGMSJF','100','购买私教','admin',now(),'购买私教送积分','CD-ZWZJ000012','CD-ZWZJ000012');
insert into `tsys_config` (`type`, `ckey`, `cvalue`, `note`, `updater`, `update_datetime`, `remark`, `company_code`, `system_code`) values('1','KCGMSJF','100','购买课程','admin',now(),'购买课程送积分','CD-ZWZJ000012','CD-ZWZJ000012');
insert into `tsys_config` (`type`, `ckey`, `cvalue`, `note`, `updater`, `update_datetime`, `remark`, `company_code`, `system_code`) values('2','ZYQZ','0.8','专业权重','admin',now(),NULL,'CD-ZWZJ000012','CD-ZWZJ000012');
insert into `tsys_config` (`type`, `ckey`, `cvalue`, `note`, `updater`, `update_datetime`, `remark`, `company_code`, `system_code`) values('2','TDQZ','0.8','态度权重','admin',now(),NULL,'CD-ZWZJ000012','CD-ZWZJ000012');
insert into `tsys_config` (`type`, `ckey`, `cvalue`, `note`, `updater`, `update_datetime`, `remark`, `company_code`, `system_code`) values('2','WDQZ','0.8','纬度权重','admin',now(),NULL,'CD-ZWZJ000012','CD-ZWZJ000012');
insert into `tsys_config` (`type`, `ckey`, `cvalue`, `note`, `updater`, `update_datetime`, `remark`, `company_code`, `system_code`) values('2','WDQZZ','0.8','纬度权重','admin','2017-07-21 13:54:33','纬度权重','CD-ZWZJ000012','CD-ZWZJ000012');
insert into `tsys_config` (`type`, `ckey`, `cvalue`, `note`, `updater`, `update_datetime`, `remark`, `company_code`, `system_code`) values('3','LXJL','0','零星教练，星数0-50','admin',now(),'11','CD-ZWZJ000012','CD-ZWZJ000012');
insert into `tsys_config` (`type`, `ckey`, `cvalue`, `note`, `updater`, `update_datetime`, `remark`, `company_code`, `system_code`) values('3','YXJL','50','一星教练，星数50-80','admin',now(),'12','CD-ZWZJ000012','CD-ZWZJ000012');
insert into `tsys_config` (`type`, `ckey`, `cvalue`, `note`, `updater`, `update_datetime`, `remark`, `company_code`, `system_code`) values('3','EXJL','80','二星教练，星数80-130','admin',now(),'12','CD-ZWZJ000012','CD-ZWZJ000012');
insert into `tsys_config` (`type`, `ckey`, `cvalue`, `note`, `updater`, `update_datetime`, `remark`, `company_code`, `system_code`) values('3','SAXJL','130','三星教练，星数130-200','admin',now(),'12','CD-ZWZJ000012','CD-ZWZJ000012');
insert into `tsys_config` (`type`, `ckey`, `cvalue`, `note`, `updater`, `update_datetime`, `remark`, `company_code`, `system_code`) values('3','SXJL','200','四星教练，星数200-300','admin',now(),'12','CD-ZWZJ000012','CD-ZWZJ000012');
insert into `tsys_config` (`type`, `ckey`, `cvalue`, `note`, `updater`, `update_datetime`, `remark`, `company_code`, `system_code`) values('3','WXJL','300','五星教练，星数300颗以上','admin',now(),'12','CD-ZWZJ000012','CD-ZWZJ000012');
insert into `tsys_config` (`type`, `ckey`, `cvalue`, `note`, `updater`, `update_datetime`, `remark`, `company_code`, `system_code`) values('4','HKFC','0.05','获客分成','admin',now(),'获客分成','CD-ZWZJ000012','CD-ZWZJ000012');
insert into `tsys_config` (`type`, `ckey`, `cvalue`, `note`, `updater`, `update_datetime`, `remark`, `company_code`, `system_code`) values('4','SJFC','0.80','私教分成','admin',now(),'私教分成','CD-ZWZJ000012','CD-ZWZJ000012');
insert into `tsys_config` (`type`, `ckey`, `cvalue`, `note`, `updater`, `update_datetime`, `remark`, `company_code`, `system_code`) values('4','WY','0.20','违约扣除比例','admin',now(),'违约扣除比例','CD-ZWZJ000012','CD-ZWZJ000012');
insert into `tsys_config` (`type`, `ckey`, `cvalue`, `note`, `updater`, `update_datetime`, `remark`, `company_code`, `system_code`) values('4','TTJFC','0.04','团课教练分成','admin',now(),'团课教练分成','CD-ZWZJ000012','CD-ZWZJ000012');
